import type { Metadata } from 'next'
import { Inter, Hanken_Grotesk, Urbanist } from 'next/font/google'
import './globals.css'
import Navbar from './components/navbar'

const inter = Inter({ subsets: ['latin'] })
const hanken = Hanken_Grotesk({ subsets: ['latin'] })
const urbanist = Urbanist({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className={urbanist.className}>
      <meta name="theme-color" content={"#FFFFFF"} />
      <body className='overflow-y-scroll overflow-y-visible'>
        {/* <Navbar /> */}
        {children}
      </body>
    </html>
  )
}
